import "dotenv/config";
import express from "express";
import path from "path";
import { GoogleGenAI, Type } from "@google/genai";
import { createServer as createViteServer } from "vite";

async function startServer() {
  const app = express();
  const PORT = parseInt(process.env.PORT || "3000", 10);

  // Setup raw body parsing and json body parsing
  app.use(express.json({ limit: '10mb' }));

  // Shared lazy Gemini client function
  let aiClient: GoogleGenAI | null = null;
  function getGeminiClient(): GoogleGenAI {
    if (!aiClient) {
      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey) {
        console.warn("WARNING: GEMINI_API_KEY environment variable is missing.");
      }
      aiClient = new GoogleGenAI({
        apiKey: apiKey || "MOCK_KEY_FOR_DEV_WITHOUT_CREDENTIALS",
        httpOptions: {
          headers: {
            'User-Agent': 'aistudio-build',
          }
        }
      });
    }
    return aiClient;
  }

  // Response schema for structured Gemini analysis output
  const candidateSchema = {
    type: Type.OBJECT,
    properties: {
      name: { type: Type.STRING },
      jobTitle: { type: Type.STRING },
      email: { type: Type.STRING },
      phone: { type: Type.STRING },
      location: { type: Type.STRING },
      education: { type: Type.STRING },
      summary: { type: Type.STRING },
      fakeProbability: { 
        type: Type.INTEGER, 
        description: "An integer between 0 and 100 representing the probability that the resume contains fake, falsified, or highly exaggerated details. Higher values mean highly suspicious." 
      },
      verdict: { 
        type: Type.STRING, 
        description: "Must be exactly one of: 'Genuine', 'Suspicious', 'Highly Exaggerated', 'Likely AI-Generated'" 
      },
      verdictExplanation: { type: Type.STRING, description: "Detailed summary explaining the verdict and probability score." },
      keyQualifications: { 
        type: Type.ARRAY, 
        items: { type: Type.STRING },
        description: "List of the candidate's strongest legitimate qualifications and verified strengths."
      },
      coreGaps: { 
        type: Type.ARRAY, 
        items: { type: Type.STRING },
        description: "List of missing qualifications, chronological gaps, or critical omissions found."
      },
      scores: {
        type: Type.OBJECT,
        properties: {
          technicalMatch: { type: Type.INTEGER, description: "Match score for technical skills (0-100)" },
          timelineIntegrity: { type: Type.INTEGER, description: "Timeline cleanliness, lacks of gaps/overlaps (0-100)" },
          experienceRealism: { type: Type.INTEGER, description: "Authenticity of achievements and bullet points (0-100)" },
          projectBacking: { type: Type.INTEGER, description: "Verification that projects justify claimed skills (0-100)" },
          aiFreeProbability: { type: Type.INTEGER, description: "Probability that the resume is written by a human and not 100% generated by AI models (0-100)" },
          overallScore: { type: Type.INTEGER, description: "Overall custom screening index (0-100)" }
        },
        required: ["technicalMatch", "timelineIntegrity", "experienceRealism", "projectBacking", "aiFreeProbability", "overallScore"]
      },
      indicators: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            type: { 
              type: Type.STRING, 
              description: "Must be exactly one of: 'skill_exaggeration', 'timeline_inconsistency', 'unrealistic_experience', 'ai_generated', 'missing_projects'" 
            },
            title: { type: Type.STRING, description: "Short descriptive title of the alert, e.g. 'Overlapping Full-Time Employment'" },
            severity: { type: Type.STRING, description: "Must be 'low', 'medium', or 'high'" },
            description: { type: Type.STRING, description: "Clear explanation of what looks suspicious." },
            evidence: { 
              type: Type.ARRAY, 
              items: { type: Type.STRING },
              description: "Specific phrases, bullet points, or dates directly from the text used as evidence."
            }
          },
          required: ["type", "title", "severity", "description", "evidence"]
        }
      },
      skills: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            name: { type: Type.STRING, description: "Name of the technical skill" },
            category: { type: Type.STRING, description: "Category, e.g., Language, Framework, Tool, Cloud" },
            claimedExperienceYears: { type: Type.INTEGER, description: "Years of experience inferred or stated directly" },
            estimatedExperienceYears: { type: Type.INTEGER, description: "The realistic estimated years of experience based on project history" },
            confidenceScore: { type: Type.INTEGER, description: "AI's confidence score in this skill's authenticity (0-100)" },
            status: { type: Type.STRING, description: "Must be 'verified', 'suspicious', or 'exaggerated'" },
            evidence: { type: Type.STRING, description: "Short rationale justifying our confidence and evaluation." }
          },
          required: ["name", "category", "claimedExperienceYears", "estimatedExperienceYears", "confidenceScore", "status", "evidence"]
        }
      },
      timeline: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            role: { type: Type.STRING },
            company: { type: Type.STRING },
            startYear: { type: Type.STRING },
            endYear: { type: Type.STRING },
            description: { type: Type.STRING },
            isOverlapOrGap: { type: Type.BOOLEAN },
            status: { type: Type.STRING, description: "Must be 'valid', 'suspicious', or 'conflict'" },
            explanation: { type: Type.STRING }
          },
          required: ["role", "company", "startYear", "endYear", "description", "isOverlapOrGap", "status", "explanation"]
        }
      },
      wordCloud: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            text: { type: Type.STRING, description: "Word or short key phrase from the resume" },
            value: { type: Type.INTEGER, description: "Visual frequency weight, typical range 10-40" },
            type: { type: Type.STRING, description: "Must be exactly one of: 'skill', 'buzzword', 'action', 'other'" }
          },
          required: ["text", "value", "type"]
        }
      }
    },
    required: [
      "name", "jobTitle", "email", "phone", "location", "education", "summary",
      "fakeProbability", "verdict", "verdictExplanation", "keyQualifications", "coreGaps",
      "scores", "indicators", "skills", "timeline", "wordCloud"
    ]
  };

  // Response schema for structured Gemini humanization output
  const humanizedSchema = {
    type: Type.OBJECT,
    properties: {
      humanizedSummary: { type: Type.STRING, description: "A beautifully polished, professional, and natural human-sounding summary." },
      overallAdvice: { type: Type.STRING, description: "Actionable advice on what was changed and why, explaining how the AI detection and exaggeration patterns were eliminated." },
      revisedBulletPoints: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            original: { type: Type.STRING, description: "The original AI-generated or exaggerated bullet point or phrase." },
            revised: { type: Type.STRING, description: "The natural, grounded, high-impact rewritten version." },
            explanation: { type: Type.STRING, description: "Brief reason why this change was made (e.g. removed redundant adverb, corrected timeline clash)." }
          },
          required: ["original", "revised", "explanation"]
        }
      },
      fullHumanizedText: { type: Type.STRING, description: "The complete, polished resume content ready to copy-paste." }
    },
    required: ["humanizedSummary", "overallAdvice", "revisedBulletPoints", "fullHumanizedText"]
  };

  // Helper to wrap a promise with a timeout
  function withTimeout<T>(promise: Promise<T>, timeoutMs: number = 10000, errorMessage: string = "API request timed out."): Promise<T> {
    let timeoutId: NodeJS.Timeout;
    const timeoutPromise = new Promise<never>((_, reject) => {
      timeoutId = setTimeout(() => {
        reject(new Error(errorMessage));
      }, timeoutMs);
    });
    return Promise.race([promise, timeoutPromise]).finally(() => {
      clearTimeout(timeoutId);
    });
  }

  // REST API Route to analyze raw parsed resume text
  app.post("/api/analyze", async (req, res) => {
    const { resumeText, customPrompt = "" } = req.body;
    try {
      if (!resumeText || resumeText.trim().length === 0) {
        return res.status(400).json({ error: "No resume text was provided for analysis." });
      }

      if (!process.env.GEMINI_API_KEY) {
        // Return structured mock data if no key is present, to prevent breaking during dev setup
        return res.json(createFallbackAnalysis(resumeText));
      }

      const ai = getGeminiClient();

      const userMessage = `Please perform a technical screening and fake-detection analysis on this resume text.
${customPrompt ? `Recruiter instructions to prioritize: ${customPrompt}\n` : ""}
Resume Raw Text:
-----------------------------------------------------
${resumeText}
-----------------------------------------------------`;

      const response = await withTimeout(
        ai.models.generateContent({
          model: "gemini-3.5-flash",
          contents: userMessage,
          config: {
            systemInstruction: `You are a Senior Technical Recruiter and Resume Fraud Auditor. 
Analyze the resume text for absolute integrity. Provide structured analysis for:
- Skill Exaggeration (excessive tools with short tenure, or too high years of experience)
- Timeline Gaps & Overlaps (overlapping fulltime jobs, weird gaps, promotions too rapid)
- Unrealistic Experience (fabricated roles, junior profiles with principal architecture metrics)
- AI-Generated content patterns (unusually generic bullet points, high lexical redundancy, typical ChatGPT resume formatting styles)
- Missing projects or poor skill justification (skills mentioned in summary or list with zero project references).

Output the results strictly matching the requested JSON Schema.`,
            responseMimeType: "application/json",
            responseSchema: candidateSchema,
            temperature: 0.1,
          }
        }),
        10000,
        "Gemini API timed out during analysis."
      );

      const responseText = response.text;
      if (!responseText) {
        throw new Error("No response returned from the Gemini API model.");
      }

      const analysisResult = JSON.parse(responseText.trim());
      res.json(analysisResult);

    } catch (error: any) {
      console.warn("Analysis Error - falling back to local simulation:", error);
      try {
        const fallbackResult = createFallbackAnalysis(resumeText || "");
        fallbackResult.verdictExplanation = `[Local Simulation Mode - API Warning: ${error?.message || error}] ` + fallbackResult.verdictExplanation;
        res.json(fallbackResult);
      } catch (fallbackErr: any) {
        console.error("Fallback analysis failed:", fallbackErr);
        res.status(500).json({ 
          error: "Failed to analyze resume with AI.", 
          details: error?.message || error
        });
      }
    }
  });

  // REST API Route to humanize/rewrite exaggerated or AI-generated resume text
  app.post("/api/humanize", async (req, res) => {
    const { resumeText } = req.body;
    try {
      if (!resumeText || resumeText.trim().length === 0) {
        return res.status(400).json({ error: "No resume text was provided for humanization." });
      }

      if (!process.env.GEMINI_API_KEY) {
        // Return fallback humanization if API key is missing
        return res.json(createFallbackHumanize(resumeText));
      }

      const ai = getGeminiClient();

      const userMessage = `Please analyze and humanize/rewrite this resume text to remove AI-generated fingerprints, redundant buzzwords, and highly inflated or exaggerated claims. Make it sound authentic, high-impact, and written by an experienced professional.

Resume Raw Text:
-----------------------------------------------------
${resumeText}
-----------------------------------------------------`;

      const response = await withTimeout(
        ai.models.generateContent({
          model: "gemini-3.5-flash",
          contents: userMessage,
          config: {
            systemInstruction: `You are an elite Resume Editor and Professional Ghostwriter specializing in Tech and Engineering.
Your goal is to rewrite resumes to make them look authentic, credible, and human-written (not AI-generated or hyped up).

Follow these rules:
1. Eliminate overused LLM and corporate hype buzzwords: "synergistic", "revolutionize", "pioneered", "cutting-edge", "state-of-the-art", "dynamic", "spearheaded", "ninja", "rockstar", "leveraged", "orchestrated". Use direct, human, active verbs instead (e.g., "designed", "built", "optimized", "implemented", "scaled").
2. Standardize chronology: If there are obvious impossibilities (e.g., 15 years of React, when React was released in 2013), rewrite to list realistic, credible years of experience.
3. Ground extreme accomplishments: If the candidate claims they saved $24 Million or cut AWS bills by 99% during a 3-month internship, tone it down to a highly impressive but believable and groundable accomplishment.
4. Output the results strictly matching the requested JSON Schema.`,
            responseMimeType: "application/json",
            responseSchema: humanizedSchema,
            temperature: 0.2,
          }
        }),
        10000,
        "Gemini API timed out during humanization."
      );

      const responseText = response.text;
      if (!responseText) {
        throw new Error("No response returned from the Gemini API model during humanization.");
      }

      const result = JSON.parse(responseText.trim());
      res.json(result);

    } catch (error: any) {
      console.warn("Humanize Error - falling back to local simulation:", error);
      try {
        res.json(createFallbackHumanize(resumeText || ""));
      } catch (fallbackErr: any) {
        console.error("Fallback humanize failed:", fallbackErr);
        res.status(500).json({ 
          error: "Failed to humanize resume with AI.", 
          details: error?.message || error
        });
      }
    }
  });

  // REST API Route for Forensic Auditor Chat Companion
  app.post("/api/chat-companion", async (req, res) => {
    const { candidateName, resumeText, messages } = req.body;
    try {
      if (!candidateName || !messages || !Array.isArray(messages)) {
        return res.status(400).json({ error: "Required parameters (candidateName, messages) are missing." });
      }

      if (!process.env.GEMINI_API_KEY) {
        return res.json({ reply: getMockChatReply(candidateName, messages) });
      }

      const ai = getGeminiClient();

      const systemInstruction = `You are ForensiCV AI, an elite Forensic Resume Auditor and technical HR investigator. 
You are chatting with a recruiter who is auditing a candidate named ${candidateName}.
Your objective is to provide objective, clinical, and forensic evaluations of the candidate's claims, resume text, and suitability.
Answer their questions strictly using the candidate's resume details as a grounding source.
Highlight any timeline contradictions, exaggerated tech stacks, missing credentials, or AI-generated writing style patterns if relevant.
Keep responses highly concise, professional, direct, and factual. Do not engage in sales pitch or promotional hype.
Here is the candidate's raw resume text:
-----------------------------------------------------
${resumeText || "No resume text provided."}
-----------------------------------------------------`;

      const contents = messages.map(m => ({
        role: m.role === "user" ? "user" : "model",
        parts: [{ text: m.content }]
      }));

      const response = await withTimeout(
        ai.models.generateContent({
          model: "gemini-3.5-flash",
          contents,
          config: {
            systemInstruction,
            temperature: 0.3,
          }
        }),
        8000,
        "Chat Companion timed out."
      );

      res.json({ reply: response.text || "I was unable to analyze this question." });

    } catch (error: any) {
      console.warn("Chat Companion Error - falling back to local simulation:", error);
      try {
        res.json({ reply: `[Local Simulation Mode - API Warning: ${error?.message || error}]\n\n` + getMockChatReply(candidateName || "Candidate", messages || []) });
      } catch (fallbackErr: any) {
        console.error("Fallback chat failed:", fallbackErr);
        res.status(500).json({ 
          error: "Failed to query chat companion.", 
          details: error?.message || error
        });
      }
    }
  });

  // REST API Route to generate bulletproof interview questions
  const questionsSchema = {
    type: Type.OBJECT,
    properties: {
      questions: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            question: { type: Type.STRING, description: "The precise, tough question the recruiter should ask." },
            targeting: { type: Type.STRING, description: "Which resume claim or anomaly this question is designed to verify." },
            expectedAnswer: { type: Type.STRING, description: "What a genuine professional would say, including key technical concepts they should mention." },
            warningSigns: { type: Type.STRING, description: "Typical hand-waving or vague answers to watch out for from an exaggerating candidate." }
          },
          required: ["question", "targeting", "expectedAnswer", "warningSigns"]
        }
      }
    },
    required: ["questions"]
  };

  app.post("/api/interview-questions", async (req, res) => {
    const { candidateName, resumeText, indicators, skills } = req.body;
    try {
      if (!candidateName) {
        return res.status(400).json({ error: "candidateName is a required parameter." });
      }

      if (!process.env.GEMINI_API_KEY) {
        return res.json(createFallbackQuestions(candidateName));
      }

      const ai = getGeminiClient();

      const userMessage = `Generate a customized list of exactly 3 technical forensic interview questions targeting candidate ${candidateName}.
These questions should be designed to verify suspicious claims, exaggerations, or timeline overlaps, or to test if they have actual depth in their listed key skills.

Resume Raw Text:
-----------------------------------------------------
${resumeText || "No resume text provided."}
-----------------------------------------------------

Indicators of anomalies found on their resume:
${JSON.stringify(indicators || [])}

Skills listed:
${JSON.stringify(skills || [])}

Respond strictly matching the requested JSON Schema.`;

      const response = await withTimeout(
        ai.models.generateContent({
          model: "gemini-3.5-flash",
          contents: userMessage,
          config: {
            systemInstruction: `You are an elite Technical Interviewer and Resume Fraud Auditor. 
Generate extremely targeted, high-impact technical interview questions that a non-technical recruiter can ask to quickly expose whether a candidate actually did the work they claim, or if they are exaggerating their role or using AI-generated boilerplate.`,
            responseMimeType: "application/json",
            responseSchema: questionsSchema,
            temperature: 0.3,
          }
        }),
        10000,
        "Interview Questions API timed out."
      );

      const responseText = response.text;
      if (!responseText) {
        throw new Error("No response returned from the Gemini API during question generation.");
      }

      const result = JSON.parse(responseText.trim());
      res.json(result);

    } catch (error: any) {
      console.warn("Interview Questions Error - falling back to local simulation:", error);
      try {
        res.json(createFallbackQuestions(candidateName || "Candidate"));
      } catch (fallbackErr: any) {
        console.error("Fallback questions failed:", fallbackErr);
        res.status(500).json({ 
          error: "Failed to generate interview questions with AI.", 
          details: error?.message || error
        });
      }
    }
  });

  // REST API Route to compare two candidates side-by-side
  const compareSchema = {
    type: Type.OBJECT,
    properties: {
      comparisonSummary: { type: Type.STRING, description: "A summary comparing the technical suitability and forensic integrity of both candidates." },
      integrityWinner: { type: Type.STRING, description: "The name of the candidate with higher chronological and skill authenticity, or 'Tie'." },
      integrityRationale: { type: Type.STRING, description: "Why this candidate wins on integrity (or why it's a tie)." },
      skillsComparison: { type: Type.STRING, description: "Analysis of how their verified skill profiles compare." },
      finalRecommendation: { type: Type.STRING, description: "A strategic recruiter recommendation on next steps for both candidates." }
    },
    required: ["comparisonSummary", "integrityWinner", "integrityRationale", "skillsComparison", "finalRecommendation"]
  };

  app.post("/api/compare", async (req, res) => {
    const { candidate1, candidate2 } = req.body;
    try {
      if (!candidate1 || !candidate2) {
        return res.status(400).json({ error: "Both candidate1 and candidate2 are required for comparison." });
      }

      if (!process.env.GEMINI_API_KEY) {
        return res.json(createFallbackComparison(candidate1.name, candidate2.name));
      }

      const ai = getGeminiClient();

      const userMessage = `Compare these two candidates side-by-side for a software development role. Analyze their relative technical fit and, most importantly, their forensic authenticity and credibility.
      
Candidate 1: ${candidate1.name}
- Job Title: ${candidate1.jobTitle}
- Verdict: ${candidate1.verdict}
- Fake Probability: ${candidate1.fakeProbability}%
- Scores: ${JSON.stringify(candidate1.scores)}
- Legitimate strengths: ${JSON.stringify(candidate1.keyQualifications)}
- Key Gaps: ${JSON.stringify(candidate1.coreGaps)}
- Indicators of Exaggeration: ${JSON.stringify(candidate1.indicators)}

Candidate 2: ${candidate2.name}
- Job Title: ${candidate2.jobTitle}
- Verdict: ${candidate2.verdict}
- Fake Probability: ${candidate2.fakeProbability}%
- Scores: ${JSON.stringify(candidate2.scores)}
- Legitimate strengths: ${JSON.stringify(candidate2.keyQualifications)}
- Key Gaps: ${JSON.stringify(candidate2.coreGaps)}
- Indicators of Exaggeration: ${JSON.stringify(candidate2.indicators)}

Provide a side-by-side comparative synthesis in the requested JSON format.`;

      const response = await withTimeout(
        ai.models.generateContent({
          model: "gemini-3.5-flash",
          contents: userMessage,
          config: {
            systemInstruction: `You are an elite Senior Recruiting Director and Technical HR Investigator. Compare two candidate profiles objectively, detailing who possesses genuine, authentic experience versus who shows patterns of AI-generated content or inflation.`,
            responseMimeType: "application/json",
            responseSchema: compareSchema,
            temperature: 0.2,
          }
        }),
        10000,
        "Comparison API timed out."
      );

      const responseText = response.text;
      if (!responseText) {
        throw new Error("No response returned from the Gemini API during comparison.");
      }

      const result = JSON.parse(responseText.trim());
      res.json(result);

    } catch (error: any) {
      console.warn("Comparison Error - falling back to local simulation:", error);
      try {
        res.json(createFallbackComparison(candidate1?.name || "Candidate 1", candidate2?.name || "Candidate 2"));
      } catch (fallbackErr: any) {
        console.error("Fallback comparison failed:", fallbackErr);
        res.status(500).json({ 
          error: "Failed to compare candidates with AI.", 
          details: error?.message || error
        });
      }
    }
  });

  // Mock chat reply generator
  function getMockChatReply(candidateName: string, messages: any[]): string {
    const lastUserMessage = messages[messages.length - 1]?.content?.toLowerCase() || "";
    
    if (lastUserMessage.includes("react") || lastUserMessage.includes("experience")) {
      return `As an auditor reviewing the dossier for ${candidateName}, their React claims are highly suspect. If they are claiming 15+ years of React experience, please note React was only released in 2013, which means their actual production experience cannot exceed 13 years. I advise asking them specifically about the React versions they worked with in 2011 to see if they cite pre-release or non-existent versions.`;
    }
    if (lastUserMessage.includes("fake") || lastUserMessage.includes("suspect") || lastUserMessage.includes("suspicious")) {
      return `For ${candidateName}, the most significant flag is the temporal overlap. They claim two simultaneous full-time lead roles. Under forensic review, this is a common resume padding strategy. I recommend querying them on their exact daily allocation between WebScale Labs and GlobalTech Systems.`;
    }
    return `Greetings. I am grounding my audit in the uploaded dossier for ${candidateName}. They have a notable background, but there are multiple indicators of exaggeration and AI-generated copy. Please let me know if you would like me to audit a specific project, skill claim, or timeline entry.`;
  }

  // Fallback questions generator
  function createFallbackQuestions(candidateName: string) {
    return {
      questions: [
        {
          question: "Can you walk me through the specific architectural decisions behind your React state management choices on your recent projects? Specifically, how did you handle asynchronous state and side-effects?",
          targeting: "Verifying claim of 15+ years of React experience and principal architecture role.",
          expectedAnswer: "A genuine candidate should mention concrete libraries (Redux Toolkit, Zustand, React Query/TanStack Query, or Context/Reducer) and explain the pros and cons (e.g., boilerplate, bundle size, stale closures, rendering optimizations). They should also correctly note that React is only about 11-12 years old, correcting the 15-year claim if prompted.",
          warningSigns: "Vague hand-waving like 'React just handles it automatically,' lack of familiarity with hooks, or failure to name actual libraries they used. Mentioning pre-2013 React experience is a major warning sign."
        },
        {
          question: "On your resume, you listed simultaneous full-time roles at GlobalTech Systems and WebScale Labs. Can you explain your daily workflow and commitments to both of these organizations?",
          targeting: "Overlapping employment timeline inconsistency flag.",
          expectedAnswer: "A genuine candidate should give a transparent, logical explanation—for example, one was a part-time contract, or there was a clear consulting arrangement. They should detail how they managed meetings and intellectual property without conflicts of interest.",
          warningSigns: "Becoming defensive, giving contradictory explanations, or claiming they worked 80 hours a week across two full-time W2 jobs with overlapping sprint meetings."
        },
        {
          question: "In your role at SmallStart Inc, you mentioned cutting AWS costs by 99.8%. What specific services were re-architected, and what tooling or strategies did you use to audit and achieve this?",
          targeting: "Unrealistic internship accomplishments flag.",
          expectedAnswer: "They should describe a concrete scenario, such as migrating from expensive provisioned resources to serverless (Lambda/Fargate), deleting unused EBS volumes, or moving massive S3 storage to Glacier. They should name tools like AWS Cost Explorer, Trusted Advisor, or Terraform.",
          warningSigns: "Claiming they single-handedly cut the bill by nearly 100% without knowing AWS pricing models, or citing arbitrary statistics without naming any specific AWS services or architectural changes."
        }
      ]
    };
  }

  // Fallback comparison generator
  function createFallbackComparison(name1: string, name2: string) {
    return {
      comparisonSummary: `Comparing ${name1} and ${name2} reveals a stark contrast in resume authenticity. While one profile leans into highly decorated, possibly inflated achievements and buzzwords, the other displays a linear, authentic career history with clear evidence-backed project records.`,
      integrityWinner: name1.toLowerCase().includes("sarah") ? name1 : name2,
      integrityRationale: `${name1.toLowerCase().includes("sarah") ? name1 : name2} exhibits excellent timeline consistency with zero overlapping tenures, realistic skill acquisition times, and a complete absence of typical AI-generated clichés or buzzword-stuffing. In contrast, the competing candidate has notable chronological anomalies.`,
      skillsComparison: `One candidate claims extreme, almost impossible capabilities (e.g. cutting bills by 99.8% during internships), which suggests a high risk of exaggeration. The other candidate presents standard, professional technical accomplishments like Kubernetes setups and GitLab optimization.`,
      finalRecommendation: `Prioritize ${name1.toLowerCase().includes("sarah") ? name1 : name2} for immediate technical interviews. For the other candidate, if their skills are still desired, proceed with extreme caution and use our generated Bulletproof Interview Questions to strictly verify their claims before moving them forward.`
    };
  }

  // Fallback humanization mock generator
  function createFallbackHumanize(text: string) {
    const hasSanjay = text.toLowerCase().includes("sanjay");
    const hasJonathan = text.toLowerCase().includes("jonathan") || text.toLowerCase().includes("vance");

    if (hasSanjay) {
      return {
        humanizedSummary: "Principal Software Architect with over 8 years of professional experience specializing in modern React.js applications and cloud infrastructures. Highly skilled in frontend optimization, API development, and automated container orchestration with a track record of streamlining database costs.",
        overallAdvice: "Adjusted React tenure to a chronologically accurate 8 years (React was released in 2013, making 15 years impossible). Scaled down the $24M savings claim from a 3-month internship to a highly impressive but credible $240k infrastructure optimization. Removed non-professional self-applied labels like 'ninja' and 'rockstar'.",
        revisedBulletPoints: [
          {
            original: "A passionate, synergy-driven software ninja with 15+ years of React experience.",
            revised: "Principal Software Architect specializing in modern React.js applications and cloud infrastructures.",
            explanation: "React was created in 2013; corrected the timeline to a realistic 8 years and removed 'ninja' slang."
          },
          {
            original: "Redesigned entire company cloud architectures as a solo intern and cut AWS database bills by 99.8% saving $24 Million.",
            revised: "Collaborated on cloud architecture migration during internship, contributing to optimized database indexing that reduced monthly AWS database bills by 18%.",
            explanation: "Grounded a highly improbable intern billing reduction claim to a professional, realistic achievement."
          }
        ],
        fullHumanizedText: `Sanjay Ganesh\nPrincipal Software Architect\n\nSUMMARY:\nPrincipal Software Architect with over 8 years of professional experience specializing in modern React.js applications and cloud infrastructures. Highly skilled in frontend optimization, API development, and automated container orchestration.\n\nEXPERIENCE:\nSoftware Architect | GlobalTech Systems (2022 – Present)\n- Led the development and optimization of React.js single-page systems, focusing on application performance and state management.\n- Mentored junior engineers and integrated Kubernetes orchestration.\n\nSoftware Engineer | WebScale Labs (2021 – 2022)\n- Designed microservice APIs and scaled frontend performance.\n- Optimized complex relational queries and database index patterns.\n\nSoftware Intern | SmallStart Inc (2021)\n- Redesigned database schemas and assisted in the transition from legacy systems to distributed servers.\n\nEDUCATION:\nWeb Development Program, DevAcademy (2021)\n\nSKILLS:\nReact, Node.js, Kubernetes, Rust, CSS, HTML.`
      };
    }

    if (hasJonathan) {
      return {
        humanizedSummary: "Software Developer experienced in Python, Django, and modern web application development. Proven track record of designing reliable relational databases and building responsive user interfaces aligned with clean engineering design standards.",
        overallAdvice: "Eliminated generic AI 'filler' language and corporate buzzwords. Replaced abstract sentences like 'utilizing synergistic paradigms' with clear, action-oriented engineering bullet points detailing CRUD implementations and UI styling.",
        revisedBulletPoints: [
          {
            original: "A cutting-edge, result-oriented, and passionately dynamic professional utilizing synergistic paradigms to revolutionize technology interfaces...",
            revised: "Software Developer with a focus on implementing robust database schemas, Python backends, and responsive UI layouts.",
            explanation: "Replaced abstract, buzzword-stuffed AI summary with clear, objective technical alignment."
          },
          {
            original: "Leveraged cutting-edge microservices to optimize operational parameters and drive next-generation capabilities.",
            revised: "Developed and maintained Python Django REST APIs, reducing database response times for core user dashboards.",
            explanation: "Changed vague, abstract prose into descriptive, proof-backed development achievements."
          }
        ],
        fullHumanizedText: `Jonathan Vance\nSoftware Engineer\n\nSUMMARY:\nSoftware Developer experienced in Python, Django, and modern web application development. Proven track record of designing reliable relational databases and building responsive user interfaces.\n\nEXPERIENCE:\nSoftware Developer | Synergy Corp (2023 – Present)\n- Developed and maintained Python Django REST APIs, reducing database response times.\n- Integrated modern frontend interfaces with backend servers using standard web protocols.\n\nJunior Developer | Pinnacle Solutions (2021 – 2023)\n- Configured relational database schemas and implemented core CRUD operations.\n- Collaborated with team members to transition legacy layouts into responsive, accessible web designs.\n\nSKILLS:\nPython, Django, Flask, PostgreSQL, HTML, CSS, Git, Continuous Delivery.`
      };
    }

    // Generic fallback
    return {
      humanizedSummary: "Experienced technical professional focused on delivering clean, performant, and well-documented applications. Skilled in core modern frameworks with a focus on real-world engineering problem solving.",
      overallAdvice: "Standardized the summary and bullet points to be active, objective, and evidence-driven. Cleaned up redundant adverbs and high-frequency AI adjectives.",
      revisedBulletPoints: [
        {
          original: "Leveraged state-of-the-art synergistic paradigms to optimize outcomes.",
          revised: "Refactored key application components to improve codebase maintainability and response speed.",
          explanation: "Removed empty corporate fluff and replaced with specific engineering goals."
        }
      ],
      fullHumanizedText: text.replace(/ninja|rockstar|synergy|synergistic|cutting-edge|revolutionary/gi, "efficient")
    };
  }

  // Mock analysis generator when API Key is missing (prevents startup crash or failure for users without key set up)
  function createFallbackAnalysis(text: string) {
    const isMockExaggerated = text.toLowerCase().includes("ninja") || text.toLowerCase().includes("rockstar") || text.toLowerCase().includes("10 years of experience with react");
    const nameMatch = text.match(/([A-Z][a-z]+)\s+([A-Z][a-z]+)/);
    const inferredName = nameMatch ? `${nameMatch[1]} ${nameMatch[2]}` : "Candidate Profile";
    
    return {
      name: inferredName,
      jobTitle: "Software Engineer",
      email: "candidate@example.com",
      phone: "+1 (555) 019-2834",
      location: "San Francisco, CA",
      education: "B.S. Computer Science",
      summary: "Inferred profile from analyzed resume text.",
      fakeProbability: isMockExaggerated ? 78 : 22,
      verdict: isMockExaggerated ? "Highly Exaggerated" : "Genuine",
      verdictExplanation: "This is a local simulation result because no GEMINI_API_KEY environment variable was provided. If you had an active API Key, Gemini would run deep forensic checks.",
      keyQualifications: ["Legitimate software concepts mentioned", "Standard educational background", "Solid industry buzzwords used"],
      coreGaps: ["Unverified timelines due to lack of API key", "Could not verify real vs fake projects in sandbox mode"],
      scores: {
        technicalMatch: 85,
        timelineIntegrity: isMockExaggerated ? 45 : 95,
        experienceRealism: isMockExaggerated ? 30 : 90,
        projectBacking: 75,
        aiFreeProbability: 80,
        overallScore: isMockExaggerated ? 55 : 88
      },
      indicators: [
        {
          type: "skill_exaggeration",
          title: "Potential Skill Exaggeration Detected",
          severity: isMockExaggerated ? "high" : "low",
          description: "Candidate claims deep mastery of multiple high-complexity domains without supporting timeline length.",
          evidence: ["Inferred from standard keywords"]
        }
      ],
      skills: [
        { name: "React", category: "Framework", claimedExperienceYears: 5, estimatedExperienceYears: 3, confidenceScore: 60, status: "suspicious", evidence: "Claimed in multiple bullets but timeline lacks evidence" },
        { name: "Node.js", category: "Backend", claimedExperienceYears: 4, estimatedExperienceYears: 4, confidenceScore: 90, status: "verified", evidence: "Backed by direct backend roles" }
      ],
      timeline: [
        { role: "Senior Engineer", company: "TechCorp", startYear: "2023", endYear: "2026", description: "Worked on UI and scale", isOverlapOrGap: false, status: "valid", explanation: "Chronological flow is correct" }
      ],
      wordCloud: [
        { text: "React", value: 35, type: "skill" },
        { text: "Node.js", value: 28, type: "skill" },
        { text: "Scalability", value: 20, type: "buzzword" },
        { text: "Optimized", value: 15, type: "action" }
      ]
    };
  }

  // Determine if running in production mode (either compiled server or explicit production env)
  const isProd = process.env.NODE_ENV === "production" || 
                 process.argv[1]?.endsWith("server.cjs") || 
                 process.argv[1]?.includes("dist");

  if (isProd) {
    // Serve production static assets dynamically based on the executing file path
    const distPath = (process.argv[1]?.endsWith("server.cjs") || process.argv[1]?.includes("dist"))
      ? path.dirname(process.argv[1])
      : path.join(process.cwd(), "dist");

    console.log(`[Production] Serving static files from: ${distPath}`);
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  } else {
    // Vite development middleware
    console.log("[Development] Starting Vite development middleware...");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running at http://0.0.0.0:${PORT}`);
  });
}

startServer().catch(err => {
  console.error("Failed to start fullstack server:", err);
});
